### PR TITLE
Updated to use existing css classes

### PR DESCRIPTION
**Pull request by Chris-Schnaufer**
## Description

Changed slider header partial widget to use existing CSS for styling

## Types of changes

Adjusted widget to mimic existing HTML and CSS structure to format header

## Checklist:

- [x] I have read the documentation on [CONTRIBUTING](https://github.com/AgPipeline/Organization-info) 
- [ ] My updates require a change to the documentation 
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## Hints to reviewers:

The Font styling used for slider headers should match the rest of the document for headings

### CODE REVIEW

**Comment by KristinaRiemer** [comment]
It looks like the projects and services section headers are the right color and font now, which is great. One thing is that the Services appears to be cut off for me, I don't know if that's the case for others? 
Screen Shot 2020-09-18 at 11 28 39 AM

The next step would be changing the background color of both the header and slider parts of Projects and Services to match the background of the rest of the website. The sections appear to alternate between a white and a light grey. And also changing the font color of the slider parts for both sections, cause it's white currently. 

I imagine this can be done manually by looking them up in the [style sheet](https://cdn.digital.arizona.edu/lib/arizona-bootstrap/latest/css/arizona-bootstrap.min.css) Julian used, but I don't really know how to read all of that. I wonder if it would be possible to do this automatically from the style sheet somehow? @julianpistorius any thoughts?

**Comment by Chris-Schnaufer** [comment]
@KristinaRiemer It wasn't showing that cutoff in RStudio or in Chrome. What browser are you using?

**Comment by KristinaRiemer** [comment]
@Chris-Schnaufer Firefox.

**Comment by Chris-Schnaufer** [comment]
@KristinaRiemer I have made updated. Please try this again.

**Comment by KristinaRiemer** [comment]
@Chris-Schnaufer was the last commit intended to only fix the Services header being cut off? It's not cut off anymore for me. 

Screen Shot 2020-10-09 at 11 19 59 AM

Should I create a new issue for getting the services and projects sections the same colors/fonts as the other sections?

**Comment by Chris-Schnaufer** [comment]
@KristinaRiemer The header cut off and the font color. This uses the default slider coloration for the site so if it's to be changed, we should have another ticket. What colors should the background and the text be?

**Comment by KristinaRiemer** [comment]
I kind of forgot about this color thing, I created [an issue](https://github.com/az-digitalag/organization/issues/352) that includes details about what needs to be changed.

**Review by dlebauer — APPROVED** [review]

**Pull request merged**
